services:
  django-app:
    image: django-image-stripe-app
    container_name: django_container
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - stripe-network
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/staticfiles
    networks:
      - stripe-network

networks:
  stripe-network:
    external: true


volumes:
  static_volume: