services:
  postgresql:
    image: postgres:16
    container_name: ${POSTGRES_DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    networks:
      - stripe-network
    volumes:
      - postgresql-data:/var/lib/postgresql/data


networks:
  stripe-network:
    external: true


volumes:
  postgresql-data: