[tool.ruff]
line-length = 100
target-version = "py310"
src = ["src", "myapp"]
include = ["*.py"]
exclude = ["__pycache__"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501", "E402", "F841"]