# Generated by Django 5.2.2 on 2025-06-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="percent",
            field=models.DecimalField(
                decimal_places=2, help_text="Скидка в процентах на весь заказ", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                choices=[("USD", "US Dollar"), ("RUB", "Russian Ruble")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="percent",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Налог в процентах на каждый товар в заказе",
                max_digits=5,
            ),
        ),
    ]
